version: '3'

services:
  airflow_adsum:
    image: airflow_adsum:latest

    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags

    ports:
      - "8081:8080"

    command: airflow standalone