name: Lint Airflow DAGs

on:
  push:
    branches:
      - main
      - "*-feature"
  pull_request:

jobs:
  lint:
    name: Lint Airflow DAGs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          pip install pylint
          echo "Installing requirements.txt"
          pip install -r requirements.txt

      # Step 3: Lint all DAGs using pylint
      - name: Lint DAGs with pylint
        run: |
          echo "Linting Airflow DAGs..."
          find Task_A/dags/ -name "*.py" | xargs pylint

      # Step 4: Validate DAGs using Airflow CLI
      - name: Validate Airflow DAGs
        run: |
          echo "Validating Airflow DAGs..."
          for dag_file in Task_A/dags/*.py; do
            if [[ -f "$dag_file" ]]; then
              python -m airflow dags test $(basename "$dag_file" .py) $(date -I)
            else
              echo "No DAG files found in Task_A/dags/"
            fi
          done

